spring:
  application:
    name: Mail-Payment-Service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: system
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
